import { createI18n } from "vue-i18n";


const messages = {
    en: {
        message: {
            home: "<h1>Welcome to our homepage!</h1> <p>We are a dynamic team of enthusiasts who are thrilled to welcome you to our website. Our mission is to provide the latest news, inspiration, and entertainment for our visitors. Whether you're a science lover, seeking advice on a healthy lifestyle, or simply looking to relax with engaging articles, you'll find it all and more here. Our editorial team consists of experienced journalists and passionate individuals from the fields of culture, science, and technology. We strive to deliver content that is both engaging and accessible to everyone. From in-depth reports to short articles, our content is tailored to the diverse interests and needs of our community. Additionally, we encourage active participation on our site. Do you have questions, feedback, or would you like to share your knowledge? Our experts are here to answer your questions and engage in discussions. Explore our extensive library of articles covering topics ranging from science and technology to travel, culture, and health and fitness. To stay up to date, sign up for our newsletter to receive regular updates. Thank you for visiting our site, and we are confident that you will find plenty of exciting content here. Join us in exploring and enjoying a wonderful experience in our virtual world!</p>",
            aboutus: "<h1>About Us</h1> <p>Welcome to our website! We are delighted that you're here, and we would like to share our story and values that guide our business.</p> <p>We are a team of enthusiasts who have decided to create something exceptional. Our company was founded with the aim of delivering high-quality products/services and building positive and long-lasting relationships with our customers. Customer satisfaction is at the heart of our operations. Therefore, every product or service we offer is carefully crafted to meet the highest standards. We strive for every customer to feel valued and satisfied with our solutions.</p> <p>Our team consists of experienced and creative professionals who are dedicated to their work. Each one of us brings unique skills and perspectives, which helps us create innovative solutions for our clients. We pursue excellence in what we do and continuously develop our skills to stay up to date with the latest trends and technologies.</p> <p>However, our company is not just a workplace. It is also a community that engages in charitable projects and social initiatives. We believe in giving back and helping others, which is why we actively support local organizations and initiatives that have a positive impact on our community.</p> <p>Our mission is to create valuable products/services that improve the quality of our customers' lives. We aim to be a leader in our industry and continuously raise the bar by providing innovative solutions and inspiring others to achieve success.</p> <p>Thank you for visiting our website and showing interest in our company. If you have any questions or need further information, please don't hesitate to contact us. We are here to assist you. We warmly welcome you to our community and invite you to explore our products/services and join us on our journey to success!</p>",
            buttonFirst: "Main Page",
            buttonSecond: "About Us",
            languageSwitcherText: "Change Language"
        }
    },
    pl: {
        message: {
            home: "<h1>Witaj na naszej stronie głównej!</h1> <p>Jesteśmy dynamicznym zespołem pasjonatów, którzy z radością witają Cię na naszym serwisie. Naszą misją jest dostarczanie najświeższych informacji, inspiracji i rozrywki dla naszych odwiedzających. Nie ważne, czy jesteś miłośnikiem nauki, poszukujesz porad dotyczących zdrowego stylu życia, czy po prostu chcesz się zrelaksować przy ciekawych artykułach - tutaj znajdziesz to wszystko i jeszcze więcej. Nasza redakcja składa się z doświadczonych dziennikarzy, pasjonatów kultury, nauki i technologii. Staramy się przekazywać treści w sposób zarówno interesujący, jak i zrozumiały dla każdego. Od obszernych raportów po krótkie artykuły, nasza zawartość jest dopasowana do różnorodnych zainteresowań i potrzeb naszej społeczności. Dodatkowo, zachęcamy do aktywnego udziału na naszej stronie. Masz pytania, uwagi lub chciałbyś podzielić się swoją wiedzą? Nasi eksperci są tutaj po to, aby odpowiedzieć na Twoje pytania i angażować się w dyskusje. Przejrzyj naszą rozbudowaną bibliotekę artykułów, które obejmują tematykę od nauki i technologii, przez podróże i kulturę, aż po zdrowie i fitness. Aby być na bieżąco, zapisz się do naszego newslettera, aby otrzymywać regularne aktualizacje. Dziękujemy, że odwiedzasz naszą stronę i jesteśmy pewni, że znajdziesz tutaj wiele interesujących treści. Zapraszamy do eksploracji i cieszenia się wspaniałym doświadczeniem w naszym wirtualnym świecie!</p>",
            aboutus: "<h1>O nas</h1> <p>Witaj na naszej stronie! Cieszymy się, że tu jesteś i chcielibyśmy się z Tobą podzielić naszą historią i wartościami, które kierują naszą działalnością.</p> <p>Jesteśmy zespół pasjonatów, którzy postanowili stworzyć coś wyjątkowego. Nasza firma powstała z myślą o dostarczaniu najwyższej jakości produktów/usług oraz tworzeniu pozytywnych i długotrwałych relacji z naszymi klientami. W centrum naszej działalności stawiamy zadowolenie klienta. Dlatego każdy nasz produkt czy usługa są starannie opracowane, aby spełniały najwyższe standardy. Pragniemy, aby każdy klient czuł się doceniony i zadowolony z naszych rozwiązań. Nasz zespół składa się z doświadczonych i kreatywnych profesjonalistów, którzy są oddani swojej pracy. Każdy z nas wnosi unikalne umiejętności i perspektywy, co pomaga nam tworzyć innowacyjne rozwiązania dla naszych klientów. Dążymy do doskonałości w tym, co robimy i stale rozwijamy nasze umiejętności, aby być na bieżąco z najnowszymi trendami i technologiami. Jednak nasza firma to nie tylko miejsce pracy. To również społeczność, która angażuje się w projekty charytatywne i inicjatywy społeczne. Wierzymy w dawanie i pomaganie innym, dlatego aktywnie wspieramy lokalne organizacje i inicjatywy, które mają pozytywny wpływ na nasze otoczenie.</p> <p>Naszą misją jest tworzenie wartościowych produktów/usług, które poprawiają jakość życia naszych klientów. Chcemy być liderem w naszej branży i stale podnosić poprzeczkę, dostarczając innowacyjne rozwiązania i inspirując innych do osiągania sukcesu. Dziękujemy, że odwiedziłeś naszą stronę i zainteresowałeś się naszą firmą. Jeśli masz pytania lub potrzebujesz dodatkowych informacji, nie wahaj się skontaktować z nami. Jesteśmy tutaj, aby Ci pomóc. Z przyjemnością witamy Cię w naszej społeczności i zapraszamy do odkrywania naszych produktów/usług oraz dołączenia do naszej podróży ku sukcesowi!</p>",
            buttonFirst: "Główna",
            buttonSecond: "O nas",
            languageSwitcherText: "Zmień język"
        }
    }
}

const i18n = createI18n({
    locale: 'pl',
    fallbackLocale: 'en',
    messages
})

export default i18n;